#下面这些内容是为了让MyBatis映射
#指定Mybatis的实体目录
mybatis:
  type-aliases-package: com.er.paiyipai.model
  #指定Mybatis的Mapper文件
  mapper-locations: classpath:mapper/*xml
  #打印sql
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# 应用服务 WEB 访问端口
server:
  port: 8080
#sql url
spring:
  datasource.url: jdbc:mysql://localhost:3309/paimai?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
#sql name
  datasource.username: root
#pwd
  datasource.password: root
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    connect-timeout: 10000

logging:
  level:
    com.er.paiyipai.dao: debug

#配置token的秘钥
encryptJWTKey: er
accessTokenExpireTime: 300

